services:
  - type: web
    name: aka-yazilim-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_CONTACT_COLLECTION
        value: contact_submissions
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false
